class Endpoints:
    ROOT = "/"
    HEALTH = "/health"
    REGISTER = "/register"
    LOGIN = "/login"
    USER_INFO = "/info"
    USER_DELETE = "/delete"
    USER_UPDATE = "/"
    USER_VOTE = "/vote"
    ADMIN_CANDIDATES = "/"
    ADMIN_CANDIDATE_DETAIL = "/{candidate_id}"


class ResponseMessages:
    WELCOME = "Welcome to the Voting App!"
    HEALTH_OK = "The service is up and running!"
    USER_CREATED = "User successfully created."
    USER_UPDATED = "User updated successfully."
    LOGIN_SUCCESS = "Login successful."
    USER_DELETED = "User deleted successfully."
    USER_ALREADY_EXISTS = "User with this email already exists."
    USER_NOT_FOUND = "User with this email does not exist."
    USER_INACTIVE = "User is inactive and cannot vote."
    INVALID_PASSWORD = "The password provided is incorrect."
    INVALID_TOKEN_MISSING_EMAIL = "Invalid token: missing email"
    INVALID_TOKEN_MISSING_USER = "Invalid token: missing user"
    INVALID_TOKEN = "Invalid token"
    ADMIN_UNAUTHORIZED = "Invalid admin token."
    CANDIDATE_CREATED = "Candidate successfully created."
    CANDIDATE_UPDATED = "Candidate updated successfully."
    CANDIDATE_DELETED = "Candidate deleted successfully."
    CANDIDATE_ALREADY_EXISTS = "Candidate with this name already exists."
    CANDIDATES_LIST = "Candidates retrieved successfully."
    CANDIDATE_NOT_FOUND = "Candidate not found."
    CANDIDATE_FOUND = "Candidate retrieved successfully."
    VOTE_RECORDED = "Vote recorded successfully."
    VOTE_ALREADY_CAST = "User has already voted."
    VOTE_RESULTS = "Vote results retrieved successfully."
    NO_VOTES_RECORDED = "No votes have been recorded yet."
