services:
  db:
    image: postgres:16
    container_name: voting_db
    environment:
      POSTGRES_USER: voting_user
      POSTGRES_PASSWORD: voting_password
      POSTGRES_DB: voting_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voting_user -d voting_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: voting_app
    command: uvicorn main:voting_app --host 0.0.0.0 --port 9000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  pgdata:
