services:
  app:
    build: .
    container_name: voting_app
    command: uvicorn main:voting_app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
